<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tests" />
  </ItemGroup>

	<ItemGroup>
	  <None Remove="CEvolLexer.g4" />
	  <None Remove="CEvolParser.g4" />
	</ItemGroup>

	<ItemGroup>
	  <Antlr4 Include="CEvolLexer.g4" />
	  <Antlr4 Include="CEvolParser.g4" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
		<PackageReference Include="Antlr4BuildTasks" Version="12.14.0" />
		<PackageReference Include="libLLVM" Version="21.1.8" />
		<PackageReference Include="libLLVM.runtime.win-x64" Version="21.1.8" />
		<PackageReference Include="LLVMSharp" Version="20.1.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\EvolZero.Core\EvolZero.Core.csproj" />
	  <ProjectReference Include="..\EvolZero.Generation\EvolZero.Generation.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
</Project>
